export const TipoMovimiento = Object.freeze({
  CONSIGNACION: 'CONSIGNACION',
  RETIRO: 'RETIRO',
  COMISIÓN: 'COMISIÓN',
  TRANSFERENCIA_OUT: 'TRANSFERENCIA_OUT',
  TRANSFERENCIA_IN: 'TRANSFERENCIA_IN',
  COMPRA: 'COMPRA',
  PAGO: 'PAGO',
  INTERES: 'INTERES',
});
